In [24]:
import numpy as np

In [25]:
l=[1,2,3,4,5]
a=np.array(l)

In [26]:
a.shape

(5,)

In [27]:
l1=[l,l]
b=np.array(l1)

In [28]:
print(b.shape)

(2, 5)


In [30]:
l2=[[1,2,3,4,5]]
l3=[l2,l2]
c=np.array(l3)
c.shape

(2, 1, 5)

In [40]:
l1=[7,3,4,2,4,3,2]
l2=[l1,l1,l1,l1,l1,l1]
l3=[l2,l2,l2,l2,l2]
l4=[l3,l3]
l5=[l4,l4,l4]
e=np.array(l5)
e.shape

(3, 2, 5, 6, 7)

In [48]:
l1=[7,3,4,2,4,3,2]
l2=[l1 for i in range(0,6)]
l3=[l2 for i in range(0,5)]
l4=[l3 for i in range(0,2)]
l5=[l4 for i in range(0,3)]
e=np.array(l5)
e.shape

(3, 2, 5, 6, 7)

In [51]:
e.ndim    #dimension

5

In [54]:
e.size  #size of e array

1260

In [62]:
#reshape

f= np.reshape(e, (5,-1))

In [63]:
f.shape

(5, 252)

In [94]:
ab=[[1,2,3],[1,2,3]]
g=np.array(ab)
g.shape

(2, 3)

In [95]:
#expand dimension

g1=np.expand_dims(np.expand_dims(g,axis=2),axis=2)

In [96]:
g1.shape

(2, 3, 1, 1)

In [99]:
g[0]

array([1, 2, 3])

In [102]:
g[: , : ]

array([[1, 2, 3],
       [1, 2, 3]])

In [104]:
l=[[[1,2],[1,2],[1,2]],[[1,2],[1,2],[1,2]]]
bbb=np.array(l)
bbb.shape

(2, 3, 2)

In [105]:
bbb[1:2,2:5,1:5]

array([[[2]]])